### ISSUE TITLE
create basis

### ISSUE THREAD

**Issue by tjnet** [tjnet/NewsAppSwiftMVVM#1]
## TODO

- [x] target settings of unit testing
- [x] build scheme settings
- [x] Target Membership
- [x] .gitignore
- [x] build frameworks
- [x] Link Binary with Libraries

## reference

[Dependency Injection in MVVM Architecture with ReactiveCocoa Part 2: プロジェクトの設定 - Qiita](http://qiita.com/yoichitgy/items/ab9a3c019b4e3e89c63d)
