### ISSUE TITLE
replace tableview with collectionview

### ISSUE THREAD

**Issue by tjnet** [tjnet/NewsAppSwiftMVVM#3]
## TODO

- [x] BasePresenter
- [x] BaseUI
- [x] Presenter of CollectionView
- [x] WireFrame
- [x] VC of CollectionView
- [x] UI of CollectionView
- [ ] Show Articles of CollectionView
- [ ] Show Articles of TableView
- [ ] Show Thumbnail of TableView

### RxSwift
- [ ] [RxSwift/UICollectionView+Rx.swift at master · ReactiveX/RxSwift](https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/iOS/UICollectionView%2BRx.swift)
- [ ] [Carthage/Checkouts/RxSwift/RxCocoa/iOS/UICollectionView+Rx.swift · 5e1a76289c8120b2fa372039399025eef2e62e43 · mark.sands / Searchy · GitLab](https://gitlab.asynchrony.com/mark.sands/Searchy/blob/5e1a76289c8120b2fa372039399025eef2e62e43/Carthage/Checkouts/RxSwift/RxCocoa/iOS/UICollectionView+Rx.swift)
### UICollectionView
1. [FruitsDiet/FruitsDiet at master · rshankras/FruitsDiet](https://github.com/rshankras/FruitsDiet/tree/master/FruitsDiet)
2. [UICollectionView Custom Layout Tutorial: Pinterest](https://www.raywenderlich.com/107439/uicollectionview-custom-layout-tutorial-pinterest)
### MVVM and UICollectionView
- [ ] [Dynamic Architecture and Collection View — Medium](https://medium.com/@basso.florian/dynamic-architecture-and-collection-view-6df8e729d4fe#.oc3ltf2ph)

### Feature

[【Swift】YouTube動画アプリのサンプルコード（お気に入り登録&削除） \- Qiita](http://qiita.com/menomoto/items/a833e83a339993702260)

## Swift3 & well architectured MVP(MVVM)

[ivangodfather/marvel](https://github.com/ivangodfather/marvel)

### tutorial 

~~[UICollectionView Custom Layout Tutorial: Pinterest](https://www.raywenderlich.com/107439/uicollectionview-custom-layout-tutorial-pinterest)~~
~~[\[iOS\] UICollectionView のレイアウトクラスを作成して「Pinterest」風のレイアウトを実現する ｜ Developers\.IO](http://dev.classmethod.jp/smartphone/iphone/ios-pinterest-layout/)~~

### Useful Resources

[stv\-ekushida/ios\-pinterest\-like\-ui: Pinterest風のUIサンプル](https://github.com/stv-ekushida/ios-pinterest-like-ui)
- [demonnico/PinterestSwift: This is a Swift based demo project to show how to make the transition Pinterest liked\.](https://github.com/demonnico/PinterestSwift)

### movie

[Custom Collection View Layout \- Part 2: Pinterest – \| Ray Wenderlich](https://videos.raywenderlich.com/courses/custom-collection-view-layout/lessons/2)
